import withLayout from '@/hoc/withLayout';
import Head from 'next/head';
import Link from 'next/link';
import styled from 'styled-components';
function Home() {
  return (
    <>
      <Head>
        <title>PREAT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Wrapper>
          <Link href="/join">회원가입</Link>
          <Link href="/login">카카오 로그인</Link>
          <Link href="/login/complete">카카오로그인 완료</Link>
          <Link href="/login/loading">로딩</Link>
          <Link href="/preat">preat</Link>
          <Link href="/home">home</Link>
        </Wrapper>
      </main>
    </>
  );
}

const Wrapper = styled.div`
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding: 20px;
  font-size: 20px;
`;

export default withLayout(Home, 'home', 'home', false);
