import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>PREAT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Link href="/join">회원가입</Link>
        <Link href="/login">카카오 로그인</Link>
        <Link href="/login/complete">카카오로그인 완료</Link>
        <Link href="/login/loading">로딩</Link>
        <Link href="/preat">preat</Link>
      </main>
    </>
  );
}
